MultiTarget/GenerateAllProjectReferences.ps1

This PR resolves [this issue](https://github.com/CommunityToolkit/Windows/actions/runs/4432135848/jobs/7787118495?pr=1). 
In PowerShell 5.1, the `-Depth 0` in `Get-ChildItem -Directory -Depth 0 -Path "$PSScriptRoot/../../components/*"` was causing it to grab directories 1 depth further than expected.

Fixed CI errors caused by -Depth 0

---

.github/workflows/build.yml
.gitignore
CommunityToolkit.Tooling.SampleGen.Tests/CommunityToolkit.Tooling.SampleGen.Tests.csproj
CommunityToolkit.Tooling.SampleGen/CommunityToolkit.Tooling.SampleGen.csproj
CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Sample.cs
CommunityToolkit.Tooling.TestGen.Tests/CommunityToolkit.Tooling.TestGen.Tests.csproj
CommunityToolkit.Tooling.TestGen/CommunityToolkit.Tooling.TestGen.csproj
CommunityToolkit.Tooling.XamlNamedPropertyRelay/CommunityToolkit.Tooling.XamlNamedPropertyRelay.csproj
CommunityToolkit.Tooling.sln

Fixes #30
As part of our initial migration here, we missed that the Source Generators were being tested as part of the main build pipeline of the Labs repo, which wasn't copied here as it wasn't as tooling specific only.
This PR adds a new independent job which runs on `linux` and pulls the repo, builds just the SG tooling projects, and then run tests against them and reports to our testspaces module.
Note: need to check the path outputs of the test files and how that gets reported...

Add Job to Build.yml to run Source Generator Tests

---

CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Sample.cs

This PR is a small change that closes #20.

Fixed generated option pane attributes being incorrectly pruned

---

MultiTarget/MultiTarget.props
MultiTarget/Uno.props
ProjectHeads/Head.Uwp.props

Consolidates the UWP NoWarn block as well
Needed for https://github.com/CommunityToolkit/Labs-Windows/pull/354

Ensure `<NoWarn>` blocks in props/proj files don't conflict and overwrite one another

---

GlobalUsings_Tests.cs
MultiTarget/MultiTarget.props
ProjectHeads/Head.WinAppSdk.props
ProjectTemplate/tests/ExampleProjectTemplateTestClass.cs

Update Microsoft.Windows.SDK.BuildTools to 10.0.22621.756
Needed for SizerBase controls to resolve platform issue with Manipulation Events (which was probably going to be needed for the test injector work we need to finish as well), so bumping this to new min version for WASDK.
1.0 is out-of-support, and 1.1 is out-of-support in a month https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/release-channels#release-lifecycle
So, keeping up-to-date is probably just going to be the new norm for us anyway.

Update to WindowsAppSDK 1.3.230331000

---

ProjectHeads/App.Head.WinAppSdk.Dependencies.props

Needed for https://github.com/CommunityToolkit/Windows/pull/20 to reference the latest version of `Microsoft.Xaml.Behaviors.WinUI.Managed`.

Updated behaviors to latest version

---

ProjectHeads/Head.Uwp.props

This PR adds PolySharp to UWP heads (tests, app) to fix errors we've seen while porting code caused by missing language features.

Add C# language polyfills to UWP heads

---

.github/workflows/build.yml
MultiTarget/Uno.props

This issue originally appeared during creation of the MarqueeText control: https://github.com/CommunityToolkit/Labs-Windows/pull/275#issuecomment-1331113635, and has appeared in several more controls since. 
In https://github.com/CommunityToolkit/Labs-Windows/pull/377#issuecomment-1452405722, we moved to use this as a workaround until the issue can be solved on the Uno side.

Suppress warnings for IDisposable exposed by Uno 

---

MultiTarget/MultiTargetIdentifiers.props
MultiTarget/PackageReferences/Uwp.props

Closes #58 
This PR makes use of the existing `HasWinUI` property. When in a library, this property can be set to 'false' to override the default. On UWP, this will prevent `Microsoft.Xaml.UI` from being included.

Made WinUI 2.x optional on uwp

---

CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Documentation.cs
CommunityToolkit.Tooling.TestGen.Tests/UIThreadTestMethodTests.cs
GlobalUsings.cs
MultiTarget/Library.props
MultiTarget/PackageReferences/Netstandard.props
MultiTarget/PackageReferences/Uwp.props
ToolkitComponent.SampleProject.props

Remove System.Collections.Immutable dependency where not needed

---

CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml
CommunityToolkit.App.Shared/Renderers/ToolkitSampleRenderer.xaml
ProjectHeads/App.Head.Uno.UI.Dependencies.props
ProjectHeads/App.Head.Uno.WinUI.Dependencies.props
ProjectHeads/App.Head.Uwp.Dependencies.props
ProjectHeads/App.Head.WinAppSdk.Dependencies.props

- **Settings stretch horizontally now**, resolving: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/90
Before:
After:
- **Hiding the Experimental bar for now**
- Hiding samples dropdown if there's only 1 sample, resolving: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/86

Gallery improvements

---

ProjectHeads/GenerateSingleSampleHeads.ps1

This would cause the 'heads' directory to not be named properly and cause subtle issues that would be unnoticed. This should be more resilient now and not prone to problems and conflicts with file handles. End behavior is exactly the same.
This change just removes the error-prone `Rename-Item` powershell step to instead use the output flag on the `dotnet new` command, end output/behavior is the same, so no functional change.
Just increased stability without a random unseen thing going on behind the scenes which causes random issues elsewhere! 🎉

Fix issue where Rename-Item would fail when generating solution with PowerShell script

---

MultiTarget/UseTargetFrameworks.ps1

Found these issues during some testing.
The UseTargetFrameworks script wasn't adjusted for the submodule yet. and had some errors being silently thrown. We no longer need to use git to suppress changes as the user can't easily commit the altered files by mistake (being in a submodule).
This also improves the log output with some helpful advice. Nothing too fancy.

Fixed and updated UseTargetFrameworks script to accommodate submodule

---

ToolkitComponent.SampleProject.props

This is a fix for a bug was that introduced in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/61 and found during investigation of https://github.com/CommunityToolkit/Windows/pull/152.
Did a binary search on the git history to find where this started. The issue would have been showing earlier if not for the bug we fixed in [this PR](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/109/files#diff-e690938467c6661c771e592e945bac7fdadff2aadc14f7a9d607c7b8f43ef95aR108).
The tfms just weren't getting enabled in CI because of this bug. I fixed it that commit, then it uncovered this issue we're having. I continued rewinding git in a binary search and manually applied the fix over it as I went to find where the problem was introduced.
This issue stops if you …

Fixed an issue building sample projects on macOS

---

CommunityToolkit.App.Shared/App.xaml.cs
CommunityToolkit.App.Shared/Controls/TitleBar/NativeMethods.cs
CommunityToolkit.App.Shared/Controls/TitleBar/TitleBar.WASDK.cs
CommunityToolkit.App.Shared/Controls/TitleBar/TitleBar.cs

Fixes build errors introduced in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/88

Fixed build errors when building Wasm with WinUI 3

---

ProjectHeads/App.Head.props

dotnet build on linux doesn't like duplicated ProjectReference, left note for future See https://github.com/dotnet/msbuild/issues/2688
Missing piece for https://github.com/CommunityToolkit/Windows/pull/152
Have tested there on a pointer to this branch, though just cleaned up messaging as I found the msbuild bug to link to.
We can merge this in quick and then clean-up 152 so the tooling pointer stays on `main`. FYI @Arlodotexe

Resolve fix for converters on linux

---

ProjectHeads/App.Head.props

We need to add the Converters when running in Single Component mode, as it's only included in the all-up sample app locally (when source defined).
We also need to exclude if we're building the Converters project itself.
However, if a component itself relies on the converters and we try and to build on Linux we'll hit the original issue. Workaround for now there is to build all-up sample app instead...
Tested locally that the Converters and another component both could be built now.

Another fix for the Converters ProjectReference logic

---

.github/workflows/config/Directory.Build.props
ProjectHeads/AllComponents/Tests.Head.AllComponents.props
ProjectHeads/AllComponents/Tests.WinAppSdk/CommunityToolkit.Tests.WinAppSdk.csproj
ProjectHeads/App.Head.props
ProjectHeads/SingleComponent/Tests.Uwp/ProjectTemplate.Tests.Uwp.csproj
ProjectHeads/SingleComponent/Tests.WinAppSdk/ProjectTemplate.Tests.WinAppSdk.csproj
ProjectHeads/Tests.Head.props

From fixes in https://github.com/CommunityToolkit/Windows/pull/165
Basically, we were hitting issues locally with the project references for UWP based projects having double slashes in the paths.
However, fixing that brought up an old issue https://github.com/CommunityToolkit/Windows/pull/20#issuecomment-1514213118 which broke the CI which we didn't understand at the time.
It appears like it is again the fact we're double-referencing the packages between projects that are required to build the toolkit, since we use the toolkit itself to do so...
This normalizes the `$RepositoryDirectory` to include the `\` but then not add it when used.
Note that the `$ToolingDirectory` property is the opposite and does *not* include the `\`.

Fix the slash inclusion and apply same duplicate project fix

---

Scripts/PackEachExperiment.ps1
ToolkitComponent.SourceProject.props

Couldn't get build/PowerShell to pass properties together as one string, so added as two parameters explicitly to the script.
Tested and working as part of https://github.com/CommunityToolkit/Windows/pull/178
See commit: https://github.com/CommunityToolkit/Windows/pull/178/commits/6a14bcc0e810c4aaf23505e54b82b6aaa4382169

Pass in Date and Version PostFix separately to Pack Script

---

GenerateAllSolution.ps1
ProjectHeads/AllComponents/Wasm/wwwroot/web.config
ProjectHeads/SingleComponent/Wasm/wwwroot/web.config

While setting up CodeQL here: https://github.com/CommunityToolkit/Windows/pull/190
Was investigating issues which ended up being because of CodeQL itself stripping parameter quotes (have discussion going with them).
Anyway, based on conversations in the PowerShell Discord (much thanks to `jborean` from there), cleaned up our calls to the shell in our Generate Solutions script. Figured would be good to still keep them even though they weren't the root cause. Seems like they'll be easier to read and maintain anyway.
Using this branch to also fix CodeQL related issues. The web.config needed to be updated, I filed an Uno issue about the default value: https://github.com/unoplatform/uno/issues/13414
Going to leave as draft for a sec to see if any more hits on the next scan on the cleaned-up …

Clean-up Solution Generation PowerShell Script

---

CommunityToolkit.App.Shared/Pages/GettingStartedPage.xaml
CommunityToolkit.App.Shared/Pages/SettingsPage.xaml
CommunityToolkit.App.Shared/Pages/Shell.xaml

Addressing: https://github.com/CommunityToolkit/Windows/issues/195
- Removed  16px gap between titlebar and content:
- Added links to About card:
- Added a Documentation button at the launch page:

[Gallery] Minor tweaks

---

CommunityToolkit.App.Shared/Helpers/IconHelper.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Documentation.cs
ProjectHeads/App.Head.props

This PR closes #100, fixing an issue where png files included in the component sample library weren't showing in the sample app. 
Now that https://github.com/unoplatform/uno/issues/2502 is closed, we no longer need the library asset workaround for these files, and can include them in the csproj as library assets instead.

Removed png asset workaround for library projects

---

CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml
CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml.cs
CommunityToolkit.Tooling.SampleGen.Tests/Helpers/TestHelpers.Compilation.cs
CommunityToolkit.Tooling.SampleGen.Tests/Helpers/TestHelpers.cs
CommunityToolkit.Tooling.SampleGen.Tests/ToolkitSampleMetadataTests.Documentation.cs
CommunityToolkit.Tooling.SampleGen/Metadata/ToolkitFrontMatter.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Documentation.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleMetadataGenerator.Sample.cs
ProjectHeads/App.Head.props
ToolkitComponent.SampleProject.props

Fixes #105 
Tested in Windows repo with all the other changes here: https://github.com/CommunityToolkit/Windows/pull/204
This PR:
- Cleans up Doc Source Generator a bit using deconstructed tuple over Left.Right shenanigans
- Adds a full document registry test to look at the generated output
- Adds an `experimental` bool to YAML FrontMatter of docs we can use for Labs-Windows in the future for interleaving repos for sample apps
- Supports looking for `csproj` files in AdditionalFiles to get `ComponentName` property as well as filename for packages identity
- Updates the Sample App to have the 'Source Code' button open the Component folder on main on GitHub
- In the package flyout:
- Roughly show a good namespace for the components in the document 
- Link to both UWP and WinUI packages on …

Add Extra Metadata about csproj file to Doc Source Generator & use for Package Links in Sample App

---

CommunityToolkit.App.Shared/Pages/Shell.xaml.cs
ProjectHeads/AllComponents/Uwp/Package.appxmanifest
ProjectHeads/AllComponents/WinAppSdk/Package.appxmanifest

Porting over from my Store SDK PR as that's breaking the build, will need to figure that out after shipping. For now I can merge that in locally when building the final app.
In the meantime though, seems like we should at least check-in the quick change I did orthogonal on that one to fix the Sample App Search.
Quick two-liner to just ensure the query is made lower case so we do a case-insensitive search.
And we'll search descriptions now, so it gives us a bit better 'fuzzy' search for people looking for different more general things.
Oh, and made 8.0.0 the default for sample app versions.

Fix Sample App Search

---

CommunityToolkit.App.Shared/Helpers/NavigationViewHelper.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleSubcategory.cs

Sort the Sample App Categories and Samples Alphabetically

---

CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml

We were using the OS `DropDownButton` instead of WinUI, resulting in a slightly different style and no animated icon.

Using WinUI DropDownButton

---

CommunityToolkit.App.Shared/Renderers/ToolkitSampleRenderer.xaml.cs

Fixes https://github.com/CommunityToolkit/Windows/issues/230
Not sure why we only found this out in Release mode, or I guess just from checking out on a fresh machine we used for the store build.
In either case, there was a problem where the `Environment.Newline` in C# didn't match the files being loaded by the Sample app (files seemed inconsistent which made it harder to diagnose as some samples did load).
What was happening is because the Newline wasn't detected, the code added to strip extraneous header info off of the samples before display was instead just removing all the content.
This change makes it so we only split on the single newline character `\n` instead.

Fix issue with sample displays being blank

---

ProjectHeads/App.Head.Wasm.props

MultiThreading won't make a big difference in performance since we aren't doing a lot of thread-heavy work in our sample app. This feature has been disabled for now until it's needed again or until the SharedArrayBuffer workaround is no longer needed.

Disable MultiThreading on WASM for now

---

ProjectHeads/App.Head.props
ProjectHeads/Targets/AddMultiTargetCompatibleSampleDocs.targets
ProjectHeads/Tasks/CheckMultiTarget.props

This PR:
- Fixes #5.
- Adds a new MSBuild inline task `CheckMultiTarget` to verify multi-target compatibility for the files provided to it.
- Introduces a new target `AddMultiTargetCompatibleSampleDocs` which filters markdown files based on platform compatibility.
- Includes error handling and logging in the MSBuild tasks to provide clearer feedback during build processes.
- Excludes markdown files from `obj` and `bin` directories to prevent processing unnecessary files.
- Has been tested on UWP and WASM.

Implemented new AddMultiTargetCompatibleSampleDocs target

---

ProjectHeads/App.Head.Wasm.props

This was causing issues with Rive on the latest version of the Uno Wasm Bootstrapper. Quick hotfix needed for https://github.com/CommunityToolkit/Labs-Windows/pull/485.

Remove lidbfs.js

---

CommunityToolkit.App.Shared/CommunityToolkit.App.Shared.projitems
CommunityToolkit.App.Shared/Helpers/NavigationViewHelper.cs
CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml
CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml.cs
CommunityToolkit.App.Shared/Styles/Buttons.xaml
CommunityToolkit.App.Shared/Styles/ItemTemplates.xaml

This PR shows a yellow token in the navigation menu whenever the component is `IsExperimental` = Labs. On the component page, an `InfoBar` is added as well highlighting that this component is experimental and might change.

Adding Labs badge / infobar

---

ProjectHeads/App.Head.props
ProjectHeads/Tests.Head.props

Needed for Labs, we should be building the sample app there off the released packages.
We also need to update that so we can build any of those packages against the released version.
Needed for fix for DataTable in https://github.com/CommunityToolkit/Labs-Windows/pull/514

Update package versions to their release versions for Labs

---

MultiTarget/AvailableTargetFrameworks.props
MultiTarget/EnabledTargetFrameworks.props
MultiTarget/PackageReferences/WinAppSdk.props

Closes #160 and upgrades our tooling to use the latest stable WinAppSdk 1.4. Any components with a dependency on Microsoft.Graphics.Win2D will need to be updated to the latest 1.1.1 right away, see below for details.
Here's what I've found:
- The Extensions component (no win2d dependency) builds as expected with WinAppSdk 1.4.
- The Animations component (only depends on Extensions, no Win2d) builds as expected with WinAppSdk 1.4.
- The Media component (only depends on Animations and win2d) fails to build after updating to Wasdk 1.4 and depending on any version of Win2d (including the latest 1.1.1). 
- Upgrading the Wasdk TargetFrameworks to use `windows10.0.22621.0` instead of `windows10.0.19041.0` results in successful builds for the Media component under both the `net6-*` and `net7-*` …

Upgrade to latest stable WinAppSdk 1.4

---

ProjectHeads/Tests.Head.props

This PR fixes a typo in references to 'ToolkitExtensionSourceProject', submitted in tandem with https://github.com/CommunityToolkit/Windows/pull/318

Fixed component name typo in 'ToolkitExtensionSourceProject'

---

CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml
MultiTarget/PackageReferences/Uno.props

Related to https://github.com/CommunityToolkit/Windows/issues/281
Bump Uno Platform target version to 5.0.48

feat: Bump to Uno 5.x

---

MultiTarget/PackageReferences/WinAppSdk.props

This PR bumps our WinAppSDK dependency to the latest release version. It contains important fixes needed to add the `net8.0-windows*` TargetFramework to our packages. 
See release notes: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-144-14231219000

Update WinAppSdk to latest 1.4.4 (1.4.231219000)

---

GenerateAllSolution.ps1

Closes #166 
This fixes the CI failures that started to occur after the latest GitHub Actions image update, which updated PowerShell to 7.4.0 LTS by default for ubuntu-22.04.

Fix CI failure after update to PowerShell 7.4.0

---

Scripts/PackEachExperiment.ps1

Fixed an issue preventing PackEachExperiment.ps1 script from running from any directory

Hotfix: pack script now runs from any directory

---

MultiTarget/Library.props
ToolkitComponent.SampleProject.props
ToolkitComponent.SourceProject.props

This PR fixes a regression introduced in c7ae0a0cd562080c09a507df12103ec3b84aff9c that caused the wrong PackageId to be produced for some packages.
Importing MSBuild.Sdk.Extras in the place we did caused PackageId to be defined with a default. Our tooling doesn't reassign PackageId when there's an existing value, so the value defined by MsBuild/Extras was being used instead.
Before
After

Fixed PackageId being overridden by MSBuild.Sdk.Extras import

---

MultiTarget/PackageReferences/WinAppSdk.props

This PR updates our dependencies on Microsoft.WindowsAppSdk and Microsoft.Windows.Sdk.BuildTools to their latest stable releases.
Notably, this updates Microsoft.WindowsAppSdk to the stable 1.5 release.

Update Microsoft.WindowsAppSdk to latest stable 1.5

---

MultiTarget/PackageReferences/Uno.props

This PR updates our dependencies on Uno.UI, Uno.WinUI, etc., to the latest stable 5.1 release.
See the [blog post](https://platform.uno/blog/uno-platform-5-1/) for Uno 5.1 for more details on what this bring for consumers of toolkit packages.

Update Uno to 5.1.75

---

Build-Toolkit-Components.ps1

This PR fixes a minor issue with the `./tooling/MultiTarget/Build-Toolkit-Components.ps1` script where components would get incorrectly skipped for build depending on the contents of their `MultiTarget.props`.

Fixed components with non-default MultiTargets being skipped for build

---

MultiTarget/WinUI.Extra.props

Closes #185
This PR introduces a small packaging workaround that improves the error message when consuming the Toolkit from a project that needs to update the Windows version in their WinAppSDK TFM. 
_Originally posted in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/185#issuecomment-2049782615_
> One of the possible changes to avoid error messages of this kind is to add `lib/net7.0-windows10.0.18362` and `lib/net8.0-windows10.0.18362` folder with a `_._` file in most uno-referencing packages. This would prevent transitive dependencies to go to the wrong TargetFramework. It won't allow for the build to work, but it would not be that much misleading.

Improved error message when consuming from Uno projects with mismatched TFMs

---

Build-Toolkit-Docs.ps1

This PR contains two fixes applied to `./Build-Toolkit-Docs.ps1` made while putting together [this PR](https://github.com/MicrosoftDocs/CommunityToolkit/pull/393).
See commits for list of full changes.

Minor fixes to Build-Toolkit-Docs.ps1

---

MultiTarget/AvailableTargetFrameworks.props
MultiTarget/DefinedConstants.props
MultiTarget/EnabledTargetFrameworks.props
ProjectHeads/Head.WinAppSdk.props
ToolkitComponent.SourceProject.props

This PR contains the tooling changes needed to enable [AoT](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows) functionality on net8/WinAppSdk:
- Enables Aot when running under .NET 8 in release mode
- Defines missing `NET8_0_OR_GREATER` compilation conditionals
- Switches to net8 as the primary TFM for the WinAppSDK head

Enable AoT for net8 in Release

---

CommunityToolkit.App.Shared/App.xaml.cs
CommunityToolkit.App.Shared/Pages/Shell.xaml.cs
CommunityToolkit.App.Shared/Pages/TabbedPage.xaml.cs
MultiTarget/AvailableTargetFrameworks.props
MultiTarget/EnabledTargetFrameworks.props
MultiTarget/PackageReferences/Uno.props
ProjectHeads/App.Head.Wasm.props
ProjectHeads/SingleComponent/WinAppSdk/ProjectTemplate.WinAppSdk.csproj

This PR:
- Updates our Uno packages to the latest stable version
- Closes #182. Updates the TFMs that Uno runs on from net7.0 to net8.0
- Fixes any issues that arise from the move to net8.0

Update Uno version, Uno TFMs to .NET 8

---

CommunityToolkit.App.Shared/Helpers/NavigationViewHelper.cs

The change in this PR makes it easier to manage grouped navigation items in the sample gallery by keeping grouped items collapsed until the page is opened. 
Usability improvement is especially noticeable when expanding multiple groups with many items.
Before:
After:

Improved navigation, keep GroupNavigationItemData collapsed until needed

---

CommunityToolkit.App.Shared/Pages/GettingStartedPage.xaml
CommunityToolkit.App.Shared/Pages/GettingStartedPage.xaml.cs
CommunityToolkit.App.Shared/Pages/SettingsPage.xaml
CommunityToolkit.App.Shared/Pages/SettingsPage.xaml.cs
ProjectHeads/AllComponents/WinAppSdk/Package.appxmanifest
ProjectHeads/Head.Uwp.props

Update PolySharp to 1.14.1
TODO: Didn't check if this works in WASDK?
Another update from getting sample app ready.

Pickup version from Package to use in Settings and GettingStartedPage

---

GenerateAllSolution.ps1

Disabled consolelogger in our solution generation script to avoid https://github.com/microsoft/slngen/issues/451 until it is fixed

Disable consolelogger, add tracking issue

---

Build-Toolkit-Components.ps1

This is blocking release where we don't have a PreviewVersion postfix to our build number.

Build-Toolkit-Components.ps1 to not require PreviewVersion parameter

---

MultiTarget/WinUI.Extra.props

For net5.0+ targets, TargetPlatformMinVersion was renamed to SupportedOSPlatformVersion. See https://github.com/dotnet/designs/pull/157
The dotnet SDK uses the TargetPlatformVersion property to provide a default SupportedOSPlatformVersion value if none is explicitly provided. See [https://github.com/dotnet/designs/blob/bba3216250cb29b0063bac3ebb57a542ee21ad4f/accepted/2020/minimum-os-version/minimum-os-version.md?plain=1#L73C27-L73C48](here). 
- Declares `SupportedOSPlatformVersion`, using the existing `TargetPlatformMinVersion` value. 
- ~~Fixes an issue where apps using the toolkit were no longer able to run on versions lower than 19041 (see [here](https://github.com/CommunityToolkit/Windows/discussions/429#discussioncomment-10382352)).~~ 
- After spinning up VMs for `Windows 10 Version …

Declared SupportedOSPlatformVersion for WinAppSdk

---

MultiTarget/PackageReferences/WinAppSdk.props
MultiTarget/WinUI.Extra.props

This PR updates our tooling to use Microsoft.WindowsAppSDK 1.6-preview2 and removes prior workarounds only needed for preview1.
- **Update WindowsAppSDK to preview2**
- **Update WindowsSdkPackageVersion for net6 and net8**
- **Remove workaround for wasdk 1.6 < preview2**
Progress towards https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/205

Update Microsoft.WindowsAppSDK to 1.6-preview2

---

MultiTarget/PackageReferences/WinAppSdk.props

This PR updates our tooling to use the recent Microsoft.WindowsAppSDK 1.6 stable release.
Progress towards https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/205

Update Microsoft.WindowsAppSDK to 1.6 stable

---

CommunityToolkit.App.Shared/Renderers/GeneratedSampleOptionsRenderer.xaml.cs
CommunityToolkit.App.Shared/Renderers/ToolkitSampleRenderer.xaml.cs
CommunityToolkit.Tooling.SampleGen/Metadata/IToolkitSampleGeneratedOptionPropertyContainer.cs
CommunityToolkit.Tooling.SampleGen/Metadata/ToolkitSampleMetadata.cs
CommunityToolkit.Tooling.SampleGen/ToolkitSampleOptionGenerator.cs

Fixed a runtime binding exception in wasdk gallery samples where the generated options pane is used.
Closes #213

Fixed gallery crash under Wasdk 1.6

---

ToolkitComponent.SourceProject.props

Enables additional AoT analyzers by setting `CsWinRTAotWarningLevel` to 2, as suggested in https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/195#discussion_r1722185832.
Progress towards #205

Enabled CsWinRTAotWarningLevel 2

---

MultiTarget/PackageReferences/WinAppSdk.props
MultiTarget/WinUI.Extra.props

Remove webview2loader.dll from package (hopefully) - test workaround to report back to platform.
Fixes #215 
Going to open a Windows PR using this to see if it resolves the issue or not.

Fix #215 - Extra webview2 dll in nuget package

---

MultiTarget/PackageReferences/WinAppSdk.props

This pull request includes changes to the `MultiTarget/PackageReferences/WinAppSdk.props` file to conditionally include package references based on the `HasWinUI` property.
Needed by https://github.com/CommunityToolkit/Labs-Windows/pull/579

Conditionally reference WinAppSDK packages from HasWinUI prop

---

.github/workflows/build.yml
Build-Toolkit-Components.ps1
MultiTarget/AvailableTargetFrameworks.props
MultiTarget/EnabledTargetFrameworks.props
MultiTarget/UseTargetFrameworks.ps1
global.json

This PR adds conditions to the default declared TFMs for MultiTargets, enabling per-project TFM overrides without losing existing compatability with features that rely on MultiTarget declarations.

Enable TFM overrides per MultiTarget

---

MultiTarget/AvailableTargetFrameworks.props
MultiTarget/EnabledTargetFrameworks.props

Prerequisite PR https://github.com/CommunityToolkit/Windows/pull/540
Since Win2d 1.1.1 was the reason we originally bumped our Windows App SDK TFM to 22621 (see https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/161, https://github.com/microsoft/Win2D/issues/943) and 1.3.0 has reverted to 19041, we can reduce our TFM back down to 19041.

Revert WinAppSdkTargetFramework version from 22621 to 19041.

---

MultiTarget/PackageReferences/WinAppSdk.props
MultiTarget/WinUI.Extra.props

Cleans up unnecessary explicit declaration of
- The package reference `Microsoft.Windows.SDK.BuildTools`, as the same version comes from `Microsoft.WindowsAppSdk` via a transitive nuget reference.
- The package reference `Microsoft.Windows.CsWinRT`, since the CsWinRT analyzers and .dll are inside the runtime pack for the Windows SDK.
- The property `WindowsSdkPackageVersion`, since this is set automatically by the underlying SDK when running dotnet 8.0.403 or later. 
Follow up to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/217#discussion_r1813745206 and https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/217#discussion_r1813744249, closes #219.

Cleanup of WindowsAppSDK implicit properties and project references 

---

MultiTarget/PackageReferences/WinAppSdk.props

This PR fixes a package downgrade warning when the latest Win2d packages are used:
```
"C:\a\Windows\Windows\CommunityToolkit.AllComponents.sln" (Restore target) (1) ->
(Restore target) -> 
C:\a\Windows\Windows\components\ImageCropper\samples\ImageCropper.Samples.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.WindowsAppSDK from 1.6.240923002 to 1.6.240829007. Reference the package directly from the project to select a different version.  [C:\a\Windows\Windows\CommunityToolkit.AllComponents.sln]
C:\a\Windows\Windows\components\ImageCropper\samples\ImageCropper.Samples.csproj : error NU1605:  ImageCropperExperiment.Samples -> CommunityToolkit.WinUI.Controls.ImageCropper -> Microsoft.Graphics.Win2D 1.3.0 -> Microsoft.WindowsAppSDK (>= 1.6.240923002) …
```

Update Microsoft.WindowsAppSDK version in WinAppSdk.props

---

ProjectHeads/Head.WinAppSdk.props

This PR fixes the error annotations in the Gallery head when running the latest WindowsAppSDK and CsWinRT:
```
build (3, wasdk): tooling/ProjectHeads/AllComponents/Wasdk/obj/x64/Release/net8.0-windows10.0.19041.0/win-x64/Styles/ItemTemplates.g.i.cs#L13
Type 'ItemTemplates' implements generic WinRT interfaces which requires generated code using unsafe for trimming and AOT compatibility if passed across the WinRT ABI.
Project needs to be updated with '<AllowUnsafeBlocks>true</AllowUnsafeBlocks>'. 
```
See https://github.com/CommunityToolkit/Labs-Windows/actions/runs/11560414170

Enable AllowUnsafeBlocks for Gallery and Test heads under Windows App SDK

---

MultiTarget/UseTargetFrameworks.ps1

This PR fixes an issue with our `UseTargetFrameworks.ps1` script where TFMs would get disabled instead of enabled when 'all' MultiTargets are requested.
Follow-up to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/218
Unblocks https://github.com/CommunityToolkit/Labs-Windows/actions/runs/11564402747/job/32190626530

Fixed a regex issue with UseTargetFrameworks.ps1 when enabling 'all'

---

.config/dotnet-tools.json

We're seeing widespread [CI failure](https://github.com/CommunityToolkit/Windows/actions/runs/11849075557) in the uno-check step. 
```
==workloadRollbackDefinitionJsonOutputEnd==
× android (Microsoft.NET.Sdk.Android.Manifest-8.0.100 : 34.0.79/8.0.100) not 
installed.
× ios (Microsoft.NET.Sdk.iOS.Manifest-8.0.100 : 17.2.8022/8.0.100) not 
installed.
× maccatalyst (Microsoft.NET.Sdk.MacCatalyst.Manifest-8.0.100 : 
17.2.8022/8.0.100) not installed.
× macos (Microsoft.NET.Sdk.macOS.Manifest-8.0.100 : 14.2.8022/8.0.100) not 
installed.
× maui (Microsoft.NET.Sdk.Maui.Manifest-8.0.100 : 8.0.6/8.0.100) not 
installed.
```
This PR attempts to remedy the issue by updating uno-check to the [latest stable version](https://www.nuget.org/packages/uno.check).

Update uno-check version to 1.27.1

---

MultiTarget/PackageReferences/WinAppSdk.props
ProjectHeads/App.Head.WinAppSdk.Dependencies.props

We were hitting issues with ItemSource setting in WinUI 3, per similar notes in https://github.com/CommunityToolkit/Windows/issues/516 Updating CsWin32 provided better error messages (mostly to do with using `{Binding}` still in samples), but this appears to resolve the ItemsSource issue I was seeing before trying to debug https://github.com/CommunityToolkit/Windows/issues/542
With this change, at least on my x64 machine the StaggeredLayout appears to work again for WinUI 3.

Update WASDK 1.6.241114003 and CsWinRT 2.1.6 to fix issues with StaggeredLayout in WinUI 3

---

.config/dotnet-tools.json
.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/workflows/build.yml
Build-Toolkit-Components.ps1
Build-Toolkit-Gallery.ps1
CommunityToolkit.Tooling.SampleGen.Tests/CommunityToolkit.Tooling.SampleGen.Tests.csproj
CommunityToolkit.Tooling.TestGen.Tests/CommunityToolkit.Tooling.TestGen.Tests.csproj
GenerateAllSolution.ps1
MultiTarget/AvailableTargetFrameworks.props
MultiTarget/DefinedConstants.props
MultiTarget/EnabledTargetFrameworks.props
MultiTarget/MultiTargetIdentifiers.props
MultiTarget/PackageReferences/Uno.props
MultiTarget/PackageReferences/WinAppSdk.props
MultiTarget/WinUI.Extra.props
ProjectHeads/AllComponents/Wasm/CommunityToolkit.App.Wasm.csproj
ProjectHeads/App.Head.Uno.UI.Dependencies.props
ProjectHeads/App.Head.Uno.WinUI.Dependencies.props
ProjectHeads/App.Head.Uwp.Dependencies.props
ProjectHeads/App.Head.Wasm.props
ProjectHeads/App.Head.WinAppSdk.Dependencies.props
ProjectHeads/App.Head.props
ProjectHeads/SingleComponent/Wasm/ProjectTemplate.Wasm.csproj
ProjectHeads/Tests.Head.WinAppSdk.props
ProjectHeads/Tests.Head.props
ToolkitComponent.SampleProject.props
global.json

This PR updates our tooling to .NET 9.0.100, including updates to:
- TargetFrameworks
- Added alongside existing TFMs for Uno and Wasdk
- Update tooling to handle multi-tfm value for Uno
- Dockerfile and devcontainer (used by VS Code, locally & Codespaces)
- GitHub Actions CI (build.yml)
- global.json (selects dotnet version used by runtime)
- Dependent packages (Uno Platform)

Upgrade to .NET 9.0

---

.github/workflows/config/Directory.Build.props
MultiTarget/Extra.props
MultiTarget/GlobalUsings.props
MultiTarget/Library.props
MultiTarget/MultiTargetIdentifiers.props
MultiTarget/PackageReferences/Uwp/Microsoft.UI.Xaml.props
MultiTarget/WinUI.Extra.props
ProjectHeads/App.Head.props
ProjectHeads/GenerateSingleSampleHeads.ps1
ProjectHeads/Tests.Head.props

This PR:
- Organizes our GlobalUsings
- Cleans up random imports or exclusions
- Adds a `EnableGlobalUsings` property (enabled by default)
- Respects the `HasWinUI` property when importing `GlobalUsings.WinUI.cs`.
- Removes imports in various files that no longer need it
- Adds a `HasWinUI2` property to complement our existing `HasWinUI` property.
- Can be used to enable or disable references to `Microsoft.UI.Xaml` when running under UWP _without_ turning off references to WinUI (wasdk, uno) on other deployable targets.

MultiTarget updates: Organize GlobalUsings, add HasWinUI2 msbuild property

---

MultiTarget/AvailableTargetFrameworks.props

This PR adds the `net9.0-windows10.0.26100.0` TFM for UWP.

Add 'net9.0-windows10.0.26100.0' TFM to UWP

---

MultiTarget/UseTargetFrameworks.ps1

This PR fixes an issue where the `ExcludeMultiTargets` parameter passed to `UseTargetFrameworks.ps1` wasn't being reflected in the generated code. 
This led to issues in our CI, which relies on this parameter to ensure that UWP does not build for WinUI 3, and vice versa. 
Note the `net9.0-windows10.0.19041` TFM, which is only used for the wasdk MultiTarget. This is the Uwp package, so this should not be here:

Fixed ExcludeMultiTargets not working as expected

---

ProjectHeads/App.Head.props
ProjectHeads/Tests.Head.props

This PR updates the packages used by the gallery when the components aren't present in the solution to version 8.2.241223-build.1367 from the `MainLatest` feed. 
This fixes package downgrade errors when building gallery in the PR https://github.com/CommunityToolkit/Labs-Windows/pull/618

Update CommunityToolkit package references to version 8.2.241223-build.1367

---

MultiTarget/MultiTargetIdentifiers.props

Needed to disable `UseUwp` in the notifications package, which is failing in https://github.com/CommunityToolkit/Labs-Windows/pull/618.

Add 'HasWindowsUIXaml ' property

---

MultiTarget/AvailableTargetFrameworks.props
MultiTarget/EnabledMultiTargets.props
MultiTarget/UseTargetFrameworks.ps1

This pull request includes minor changes to the target framework properties and the `UseTargetFrameworks` script to ensure consistency by adding semicolons at the end of framework lists.
Changes to target framework properties:
* [`MultiTarget/AvailableTargetFrameworks.props`](diffhunk://#diff-3e274bd0c8181e6228278f26cc15080d741ef6551834c9eae565a829019975d3L29-R29): Added a semicolon at the end of the `DotnetStandardCommonTargetFramework` property value.
* [`MultiTarget/EnabledMultiTargets.props`](diffhunk://#diff-fd1a599e607d6912f632a2d1e5189e0ee82b59e95c23a809441fc256e3e06c2aL5-R5): Added a semicolon at the end of the `EnabledMultiTargets` property value.
Changes to `UseTargetFrameworks` script:
* [`MultiTarget/UseTargetFrameworks.ps1`](diffhunk://#diff-e690938467c6661c771e592e945bac7fdad …

Improve semicolon delimiter consistency, fix `IsNetstandard` property

---

CommunityToolkit.Tooling.SampleGen.Tests/CommunityToolkit.Tooling.SampleGen.Tests.csproj
CommunityToolkit.Tooling.TestGen.Tests/CommunityToolkit.Tooling.TestGen.Tests.csproj

This PR upgrades our SampleGen and TestGen projects to net8.0. 
This fixes a build error (see [here](https://github.com/CommunityToolkit/Tooling-Windows-Submodule/actions/runs/12694712500/job/35385085749?pr=245)) caused by the removal of net6.0 in the CI images.

Update target framework to .NET 8 for SampleGen and TestGen

---

.config/dotnet-tools.json
ProjectHeads/App.Head.Wasm.props

This PR updates our uno.check version to the latest 1.27.4

Update uno.check tool version to 1.27.4

---

Build-Toolkit-Components.ps1

Fixes #252
Our build script will now skip building components that don't target the specific WinUI version requested.
Notably, while this doesn't cause issues for any components we have now, if we have any components in the future which target _no_ version of WinUI this will prevent them from compiling, while before it picked WinUI 2 or 3 at random from the CI matrix. We'll need https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/251 to fix this properly.

Skip building components that don't target the requested WinUI version

---

.config/dotnet-tools.json

This PR fixes build errors that spontaneously occurred when generating the solution, likely due to a tooling update. Updating slngen to the lates version fixes the issue.

Fix solution generation issues by updating slngen

---

Build-Toolkit-Components.ps1

This PR fixes an issue with our `Build-Toolkit-Components` script where provided parameters were not being preprocessed properly before changing the EnabledMultiTargets via the `UseTargetFrameworks.ps1` script. 
This issue resulted in the `-winui` parameter not properly adjusting the expected `ExcludeMultiTargets`,  such as excluding `uwp` when WinUI 3 is requested. The result is that the uwp TFM is appearing in some WinUI packages, and this PR fixes the issue.

Fixed multitarget exclusion preprocessing before UseTargetFrameworks script call

---

MultiTarget/Extra.props

This PR fixes an issue where the Sample Gallery solution in generated in WinUI 3 mode couldn't build the libraries or gallery heads, citing "Current solution contains incorrect configurations mappings."
Issue was fixed by defining the `Platforms` property for libraries on both UWP and WinUI 3, instead of just UWP. It was presumed (given advice from @Sergio0694 iirc) that the SDK would define this property for us, but the behavior here suggests otherwise and has been corrected.

Fix wasdk Sample Gallery not building

---

CommunityToolkit.App.Shared/Pages/Shell.xaml.cs

This PR sets the focus to the search box in the title bar when the app is loaded.
Closes CommunityToolkit/Windows#651.

Set focus to the search box when the app is loaded

---

ProjectHeads/SingleComponent/Tests.Uwp/Package.appxmanifest
ProjectHeads/SingleComponent/Tests.Uwp/ProjectTemplate.Tests.Uwp.csproj
ProjectHeads/SingleComponent/Tests.Wasdk/Package.appxmanifest
ProjectHeads/SingleComponent/Tests.Wasdk/ProjectTemplate.Tests.Wasdk.csproj
ProjectHeads/SingleComponent/Uwp/ProjectTemplate.Uwp.csproj
ProjectTemplate/tests/ExampleProjectTemplateTestClass.cs
ProjectTemplate/tests/ExampleProjectTemplateTestPage.xaml
ProjectTemplate/tests/ExampleProjectTemplateTestPage.xaml.cs
ProjectTemplate/tests/ProjectTemplate.Tests.projitems

Close #272
Full list of changes can be found in the linked issue.

Remove "Experiment" from RootNamespace and AssemblyName

---

CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml
CommunityToolkit.App.Shared/Renderers/ToolkitDocumentationRenderer.xaml.cs

See https://github.com/CommunityToolkit/Windows/issues/587 
At least in part, there's many inconsistencies in the Labs packages from changes to templates. Both in inclusion of `.Labs.` in package as well as `.Controls.` or not.
Something we should fix in the Labs repo so everything is consistent with how the packages are named (between source, csproj props, and nuget packages).
That will make some of this code obsolete, but should just work, so we can commit here and fix in Labs after so the sample app can be correctly pointing to all packages.
(Note it's hard to copy labs components into the main repo, and vice-versa due to dependencies. We need a method in labs where we reference toolkit components differently so we can just assign properties for project reference vs. package reference, …

Initial take on fixing sample app source/package links for Labs experimental components

---

.github/workflows/config/nuget.config
ProjectHeads/App.Head.props
ProjectHeads/Tests.Head.props

This PR fixes an issue where opening or building the solution results in an error "Error occurred while getting package vulnerability data".

Removed the MainLatest feed from nuget.config, update to 8.2

---

Build-Toolkit-Docs.ps1

Fixed an issue where inline mslearn code samples weren't generated when `[ToolkitSample(somevalue)]` is used instead of `[ToolkitSample(id: somevalue)]` 
Closes https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/276

Fixed inline code samples being excluded during MSLearn doc gen

---

Get-Changed-Components.ps1

Added a simple script that outputs the list of component names with changes in git within a given commit patch range.
When something is changed outside the list of components, e.g. in tooling, 'all' is returned.
The value yielded by this script can be plugged into the variable for all existing build and solution generation scripts.
Adapted from https://github.com/CommunityToolkit/Labs-Windows/pull/647, this code has been tested and validated.

Added Get-Changed-Components.ps1

---

Get-Changed-Components.ps1

Refactored the logic here to not assume individual changed components when non-component changes aren't found.
- Added comments explaining the rationable and methodology.
- Now returns 'all' instead of empty component list.
- Added variable output for debugging CI runs.
- Added error output in case of unhandled code paths.

Logic fix for Get-Changed-Components.ps1

---

Get-Changed-Components.ps1

Follow up to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/283 after failures found in https://github.com/CommunityToolkit/Labs-Windows/pull/671. Seems that anything written to stdout is taken as the env variable, including the debug output that was added to help us guard against future issues.

Remove debug output statements from Get-Changed-Components.ps1

---

GenerateAllSolution.ps1

Minor PR that adds a `Launch` parameter to the solution generation script

Add Launch parameter to GenerateAllSolution script

---

Build-Toolkit-Components.ps1
MultiTarget/Filter-Supported-Components.ps1
MultiTarget/Get-MultiTargets.ps1
MultiTarget/Test-Component-Support.ps1

This PR:
-  Extracts MultiTarget/WinUI code checks from `Build-Toolkit-Components.ps1` into a dedicated script `Test-Component-Support.ps1`.
- Adds a new script `Filter-Supported-Components.ps1` as a one-liner for filtering (or populating) a list of toolkit components based on whether they support the given WinUI and MultiTarget preferences.
- This is needed to fix workflow issues with incremental component builds over in Labs, see https://github.com/CommunityToolkit/Labs-Windows/actions/runs/15497274118/job/43639235687#step:14:1

Refactor MultiTarget scripts for checking component support

---

Get-Changed-Components.ps1

Fixes the `Get-Changed-Components.ps1` script to avoid adding unecessary single quotes around items in the output list.
Follow-up to https://github.com/CommunityToolkit/Labs-Windows/pull/682
Should fix the remaining CI issue in https://github.com/CommunityToolkit/Labs-Windows/actions/runs/15547161141/job/43770803845?pr=680

Fix output formatting for changed component list

---

Get-Changed-Components.ps1

Ensure orphaned commits from force-pushes are always available for diffing by fetching the specified FromSha

 Handle force pushes for incremental builds
